[package]
name = "example-e"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
axum = "0.6.12"
futures = "0.3.27"
tokio = { version = "1.26.0", features = ["full"] }
