[package]
name = "F2-execve"
version = "0.1.0"
edition = "2021"
default-run = "F2-execve"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.139"


